name: Update Design Tokens
on:
  repository_dispatch:
    types: [test]

jobs:
  generate-tokens:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get current date and time
        id: datetime
        env:
          TZ: 'Asia/Tokyo'
        run: echo "current_datetime=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

      - name: Setup Node.js
        run: echo "NODE_VERSION=$(cat .node-version)" >> $GITHUB_ENV
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup pnpm
        shell: bash
        run: |
          pnpm=$(cat package.json | jq -r .engines.pnpm)
          echo "PNPM_VERSION=${pnpm}" >> $GITHUB_ENV
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: pnpm install

      - name: Run generate-tokens script
        run: >
          FIGMA_FILE_KEY=${{ secrets.FIGMA_FILE_KEY}}
          FIGMA_PERSONAL_ACCESS_TOKEN=${{ secrets.FIGMA_PERSONAL_ACCESS_TOKEN}}
          pnpm design-tokens build

      - name: Check for changes
        id: changes
        run: |
          if [[ `git status --porcelain` ]]; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Create pull request
        if: steps.changes.outputs.has_changes == 'true'
        env:
          TZ: 'Asia/Tokyo'
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: 'chore(design-tokens): update design tokens'
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: update-design-tokens-${{ steps.date.outputs.current_datetime }}
          base: ${{ github.event.repository.default_branch }}
          title: 'chore(design-tokens): Update design tokens triggered by Figma Webhook'
          body: 'Automatically generated by GitHub Actions workflow'
          reviewers: 'taigakiyokawa'
